<a href="https://colab.research.google.com/github/shivamsingh163248/IIT-Ropar-Minor-in-AI/blob/main/IIT_Ropar_Minor_in_AI/VideoLacture/TH_W1L5_Crack_the_Code_Problem_Solving_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#learning the binnery operator in the number
a = 10 ;
b =24  ;
print(a&b)

8


In [ ]:
a = True ;
print(~a);

-2


In [ ]:
#creating the simple boolen codion code
a = 10 ;
b = 20 ;

if(a>5 and b>5):
  print("correct") ;
else:
  print("incorrect") ;

correct


In [ ]:
#we  write the same code in the bracket
#creating the simple boolen codion code
a = 10 ;
b = 20 ;

if(a>5 and b>5):
      print("correct") ;
else :
     print("incorrect") ;


correct


In [ ]:
#creating the program that are the creating  all the deta type and the print them
my_string = "shivam singh"
my_boolen  = True
my_char  = 'c'
my_int = 10

print(f"integer:{my_int}")
print(f"string:{my_string}")
print(f"boolen:{my_boolen}")
print(f"char:{my_char}")

integer:10
string:shivam singh
boolen:True
char:c


In [ ]:
#creating the filps
filps = ['H' , 'T' , 'H' , 'T','H' , 'T' , 'T','T']
#creating the h count and t count
h_count =  0 ;
t_count = 0 ;

# h_count = h_count+1 ;

#creating the loop
for f in filps:
  if(f == 'H'):
    h_count = h_count+1 ;
  else:
    t_count = t_count+1 ;

print(h_count)
print(t_count)

3
5


In [ ]:
import numpy as np
arr = np.array([[1,3,-1],[2,4,-2]])
print(f"{arr[1,0]} and {arr[0][-1]}")


2 and -1


In [ ]:
import numpy as np
a = np.ones((2,  3,  4))
b = np.ones((3,  4))
result = a + b
print(result)


[[[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]

 [[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]]


In [ ]:
import numpy as np
a = np.ones((2,  3,  4))
b = np.ones((3,  4))
result = a + b
print(result)


[[[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]

 [[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]]


In [ ]:
#learning the break and continue with the while loop
i = 1
while (i<10):
    #creating the constrain on the loop pf the brak
    if i ==5 :
        break
    print(i , end = ' ')
    i += 1

print("done")

#creating the continue statement
j  = 1
while (j < 10):
  if(j == 5):
    continue
  else:
    print(j , end = ' ')
  j += 1

print("done")

1 2 3 4 done
1 2 3 4 

In [1]:
import numpy as np
arr = np.ones((3,3))
arr[1, 1] = 5
print(arr)


[[1. 1. 1.]
 [1. 5. 1.]
 [1. 1. 1.]]


In [2]:
import numpy as np
np1 = np.array([10, 20, 30, 40, 50, 60])
print(np1[1:-1:2])


[20 40]
